yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('change/', views.change, name='change'),
    path('logout/', views.logout_view,
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_change/',
         PasswordChangeView
         .as_view(template_name='users/password_change_form.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView
         .as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         PasswordResetView
         .as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView
         .as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView
         .as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView
         .as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.db import models


class Group(models.Model):
    title = models.CharField('Название сообщества', max_length=200)
    slug = models.SlugField('Ссылка сообщества', unique=True)
    description = models.TextField('Описание сообщества', max_length=300)

    class Meta:
        verbose_name = 'сообщество'
        verbose_name_plural = 'сообщества'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст записи', help_text='Текст вашей записи')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Выберите сообщество:',
        help_text='Сообщество для вашей записи',
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Добавить картинку',
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'запись'
        verbose_name_plural = 'записи'

    def __str__(self):
        return self.text[:settings.CUT_TEXT]


class Comment(models.Model):
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    post = models.ForeignKey(
        Post,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='comments',
        verbose_name='Запись'
    )

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

    def __str__(self):
        return self.text[:settings.CUT_TEXT]


class Follow(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'подписчик'
        verbose_name_plural = 'подписчики'

    def __str__(self):
        return self.user.username

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import get_user_model

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .utils import paginator

User = get_user_model()


def index(request):
    """Главная страница с записями."""
    posts = Post.objects.select_related('author', 'group')
    context = {
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Страница сообществ с записями."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    context = {
        'group': group,
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Страница автора с его записями."""
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    following = Follow.objects.filter(
        user=request.user.id, author__following__author=author)
    context = {
        'author': author,
        'following': following,
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Страница одной записи."""
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.select_related('author')
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required()
def post_create(request):
    """Функция создания записи."""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Функция редактирования записи."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_delete(request, post_id):
    """Функция удаления записи."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    post.delete()
    return redirect('posts:profile', post.author.username)


@login_required
def add_comment(request, post_id):
    """Функция создания комментариев."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    """Функция страницы с подписками."""
    posts = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user)
    context = {
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Функция подписки на автора."""
    author = get_object_or_404(User, username=username)
    follower = request.user
    if follower != author and follower != author.follower:
        Follow.objects.get_or_create(user=follower, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Функция отписки от автора."""
    Follow.objects.filter(
        user=request.user,
        author__username=username
    ).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/includes/comments.html
{% load user_filters %}
<div class="card my-3">
  <h5 class="card-header">Комментариев к записи: {{ post.comments.count }}</h5>
	{% for comment in comments %}
	  <div class="card-body">
      <div class="card my-sm-0">
		    <div class="card-body">
          <h6 class="card-title">
				  <a class="text-muted" href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.username }}</a>
				  <span class="text-muted">{{ comment.created }}</span>
			    </h6>
			    <p class="card-text">{{ comment.text|linebreaksbr }}</p>
		    </div>
		  </div>
		</div>
	{% endfor %}
</div>
{% if user.is_authenticated %}
  <div class="card my-2">
		<h5 class="card-header">Добавить комментарий:</h5>
		<div class="card-body">
			<form method="post" action="{% url 'posts:add_comment' post.pk %}">
			{% csrf_token %}
			<div class="form-group mb-2">
				{{ form.text|addclass:"form-control" }}
				<small id="{{ form.text.id_for_label }}-help" class="form-text text-muted">{{ form.text.help_text|safe }}</small>
			</div>
				<button type="submit" class="btn btn-success">Отправить</button>
			</form>
    </div>
  </div>
{% else %}
  <p><a class="text-muted" href="{% url 'users:login' %}">Войдите</a> или <a class="text-muted" href="{% url 'users:signup' %}">зарегистрируйтесь</a>, чтобы оставить комментарий.</p>
{% endif %}

yatube/templates/posts/includes/latest_posts.html
{% load user_filters %}
<div class="card my-2">
  <h6 class="card-header">Последние записи:</h6>
    <div class="card-body">
			<ul>
				{% for post in latest_posts %}
					<li><a class="text-muted" href="{% url 'posts:post_detail' post.pk %}">{{ post.text|truncatechars_html:30 }}</a></li>
				{% endfor %}
			</ul>
		</div>
</div>

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link text-muted" href="?page=1">Первая</a></li>
        <li class="page-item">
        <a class="page-link text-muted" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link text-muted" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link text-muted" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link text-muted" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}    
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/includes/post_card.html
{% load thumbnail %}
  <div class="card mb-4">
    <div class="card-header">
			{% if author %}
				<h6 class="card-title">Автор: {{ post.author.get_full_name }}</h6>
			{% else %}
				<h6 class="card-title">Автор: <a class="text-muted" href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a></h6>
			{% endif %}
				<span class="text-muted">Дата публикации: {{ post.pub_date|date:"d E Y H:i" }}</span>
    </div>
    <div class="card-body">
      {% thumbnail post.image "960x350" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% if post.text|length > 300 %}
        <p class="card-text">{{ post.text|truncatechars_html:300|linebreaksbr }}</p>
        <p><a href="{% url 'posts:post_detail' post.pk %}" class="btn btn-outline-dark btn-sm">Читать далее</a></p>
      {% else %}
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
        <p><a href="{% url 'posts:post_detail' post.pk %}" class="btn btn-outline-dark btn-sm">Читать далее</a></p>
      {% endif %}
    </div>
    {% if not group %}
      <div class="card-footer">
				<div class="row">
					<aside class="fluid">
						{% if post.group %}
							Сообщество: <a class="text-muted" href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
						{% else %}
							<span style='color:gray'>Этой записи нет ни в одном сообществе</span>
						{% endif %}
					</aside>
				  <article class="fluid">
						{% if post.comments.count > 0 %}
					    Комментариев: <a class="text-muted" href="{% url 'posts:post_detail' post.pk %}">{{ post.comments.count }}</a>
						{% endif %}
					</article>
				</div>
      </div>
    {% endif %}
  </div>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
	<nav class="navbar navbar-expand bg-light">
		<div class="container-fluid">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link text-muted {% if view_name == 'posts:index' %}active{% endif %}" href="{% url 'posts:index' %}">
						Все записи
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-muted {% if view_name == 'posts:follow_index' %}active{% endif %}" href="{% url 'posts:follow_index' %}">
						Мои подписки
					</a>
				</li>
			</ul>
		</div>
	</nav>
{% endif %}