yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('change/', views.change, name='change'),
    path('logout/', views.logout_view,
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_change/',
         PasswordChangeView
         .as_view(template_name='users/password_change_form.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView
         .as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         PasswordResetView
         .as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView
         .as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView
         .as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView
         .as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.db import models


class Group(models.Model):
    title = models.CharField('Название сообщества', max_length=200)
    slug = models.SlugField('Ссылка сообщества', unique=True)
    description = models.TextField('Описание сообщества', max_length=300)

    class Meta:
        verbose_name = 'сообщество'
        verbose_name_plural = 'сообщества'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст записи', help_text='Текст вашей записи')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Выберите сообщество:',
        help_text='Сообщество для вашей записи',
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Добавить картинку',
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'запись'
        verbose_name_plural = 'записи'

    def __str__(self):
        return self.text[:settings.CUT_TEXT]


class Comment(models.Model):
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    post = models.ForeignKey(
        Post,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='comments',
        verbose_name='Запись'
    )

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

    def __str__(self):
        return self.text[:settings.CUT_TEXT]


class Follow(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'подписчик'
        verbose_name_plural = 'подписчики'

    def __str__(self):
        return self.user.username

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import get_user_model

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .utils import paginator

User = get_user_model()


def index(request):
    """Главная страница с записями."""
    posts = Post.objects.select_related('author', 'group')
    context = {
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Страница сообществ с записями."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    context = {
        'group': group,
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Страница автора с его записями."""
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    following = Follow.objects.filter(
        user=request.user.id, author__following__author=author)
    context = {
        'author': author,
        'following': following,
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Страница одной записи."""
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.select_related('author')
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required()
def post_create(request):
    """Функция создания записи."""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Функция редактирования записи."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_delete(request, post_id):
    """Функция удаления записи."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    post.delete()
    return redirect('posts:profile', post.author.username)


@login_required
def add_comment(request, post_id):
    """Функция создания комментариев."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    """Функция страницы с подписками."""
    posts = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user)
    context = {
        'page_obj': paginator(posts, request),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Функция подписки на автора."""
    author = get_object_or_404(User, username=username)
    follower = request.user
    if follower != author and follower != author.follower:
        Follow.objects.get_or_create(user=follower, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Функция отписки от автора."""
    Follow.objects.filter(
        user=request.user,
        author__username=username
    ).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
  {% block title %}{% if form.instance.pk %}Редактировать запись{% else %}Новая запись{% endif %}{% endblock %}
  {% block content %} 
    <div class="container py-4">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header">{% if form.instance.pk %}Редактировать запись{% else %}Новая запись{% endif %}</div>
            <div class="card-body">
              {% include 'includes/errors.html' %}    
              <form method="post" action="{% if form.instance.pk %}{% url 'posts:post_edit' form.instance.pk %}{% else %}{% url 'posts:post_create' %}{% endif %}" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'includes/forms.html' %}
                <div class="d-flex justify-content-center">
                  <button type="submit" class="btn btn-success">
                    {% if form.instance.pk %}Сохранить{% else %}Добавить{% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
  {% block title %}
    Мои подписки
  {% endblock %}
  {% block content %} 
    <div class="container py-4">
		  <div class="mb-4"><div class="mb-4"><h1 class="display-5">Последние обновления моих подписок</h1></div>
			{% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
  {% block title %}
    Записи сообщества {{ group }}
  {% endblock %}
  {% block content %} 
    <div class="container py-4">
      <div class="mb-4">
        <div class="mb-4"><h1 class="display-5">{{ group }}</h1>
        <p>{{ group.description|linebreaks }}</p>
      </div>
      {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>  
  {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
  {% block title %}
    Последние обновления на сайте
  {% endblock %}
  {% block content %}
		{% load user_filters %}
    <div class="container py-4">
		  <div class="mb-4"><h1 class="display-5">Последние обновления на сайте</h1></div>
					<div class="row my-3">
						<aside class="col-md-6">
							{% show_latest_posts 5 %}
						</aside>
						<article class="col-md-6">
							<div class="card my-2">
							<h6 class="card-header">Самые обсуждаемые записи:</h6>
							<div class="card-body">
							{% get_most_commented_posts as most_commented_posts %}
							<ul>
								{% for post in most_commented_posts %}
									<li><a class="text-muted" href="{% url 'posts:post_detail' post.pk %}">{{ post.text|truncatechars_html:30 }}</a></li>
								{% endfor %}
							</ul>
							</div>
							</div>
						</article>
					</div>
		      {% include 'posts/includes/switcher.html' %}
				<div>
				{% load cache %}
				{% cache 20 sidebar index page_obj.number %}
				{% for post in page_obj %}
				{% include 'posts/includes/post_card.html' %}
				{% endfor %}
				{% include 'posts/includes/paginator.html' %}
				{% endcache %}
				</div>
    </div>
  {% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
  {% block title %}Запись: {{ post.text|truncatechars_html:30 }}{% endblock %}
  {% block content %}
  {% load thumbnail %}
    <div class="container py-4">
        <div class="row">
          <aside class="col-12 col-md-4">
					  <div class="card my-2">
						  <h5 class="card-header">Автор {{ post.author.get_full_name }}</h5>
						  <div class="card-body">
								<ul class="list-group list-group-flush">
									<li class="list-group-item">
										{% thumbnail post.author.profile_pic "300x300" crop="center" upscale=True as av %}
											<img class="rounded mx-auto d-block" src="{{ av.url }}">
										{% endthumbnail %}
									</li>
									<li class="list-group-item">
										{% if post.author == request.user %}
											Автор: <a class="text-muted" href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
										{% else %}
											Автор: <a class="text-muted" href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
										{% endif %}
									</li>
									<li class="list-group-item">
										Дата публикации: {{ post.pub_date|date:"d E Y H:i" }}
									</li>
									<li class="list-group-item">
									{% if post.group %}
										Сообщество: <a class="text-muted" href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
									{% else %}
										<span style='color:gray'>Этой записи нет ни в одном сообществе</span>
									{% endif %}
									</li>
								  {% if post.author == request.user %}
									  <li class="list-group-item">
											Всего моих записей: <span>{{ post.author.posts.count }}</span>
										</li>
										<li class="list-group-item">
										  Всего моих подписчиков: <span>{{ post.author.following.count }}</span>
										</li>
										<li class="list-group-item">
											<a href="{% url 'posts:post_edit' post.id %}" class="btn btn-outline-success btn-sm mb-1">Редактировать запись</a>
											<a href="{% url 'posts:post_delete' post.id %}" class="btn btn-outline-danger btn-sm mb-1">Удалить запись</a>
										</li>
									{% else %}
										<li class="list-group-item">
											Всего записей автора: <span>{{ post.author.posts.count }}</span>
										</li>
										<li class="list-group-item">
										  Всего подписчиков автора: {{ post.author.following.count }}
										</li>
									{% endif %}
								</ul>
							</div>
						</div>
          </aside>
          <article class="col-12 col-md-8">
					  <div class="card my-2">
						  <h5 class="card-header">Текст записи</h5>
							<div class="card-body">
								{% thumbnail post.image "960x500" crop="center" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
								<p class="card-text">{{ post.text|linebreaksbr }}</p>
							</div>
						</div>
						{% include 'posts/includes/comments.html' %}
          </article>
        </div>
    </div>
  {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профиль автора {{ author.get_full_name }}{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-4">
    <div class="card my-2">
		  <h5 class="card-header">Автор {{ author.get_full_name }}</h5>
			<div class="card-body">
				{% if author != request.user %}
					<div class="row">
						<aside class="col-md-4">
							{% thumbnail author.profile_pic "300x300" crop="center" upscale=True as im %}
								<img class="rounded mx-auto d-block" src="{{ im.url }}"><br>
							{% endthumbnail %}
						</aside>
						<article class="col-md-8">
							<h1>Все записи автора {{ author.get_full_name }}</h1>
							<h6>Всего записей: {{ author.posts.count }}</h6>
							<h6>Подписчиков: {{ author.following.count }}</h6>
							{% if author.city != None %}<div>Город: {{ author.city }}</div>{% endif %}
							{% if author.vk != None %}<div>Вконтакте: <a class="text-muted" href="https://vk.com/{{author.vk}}" target="_blank">{{ author.vk }}</a></div>{% endif %}
							{% if author.telegram != None %}<div>Telegram: <a class="text-muted" href="https://t.me/{{author.telegram}}" target="_blank">{{ author.telegram }}</a></div>{% endif %}
							{% if author.instagram != None %}<div>Instagram: <a class="text-muted" href="https://instagram.com/{{author.instagram}}" target="_blank">{{ author.instagram }}</a></div>{% endif %}
							{% if author.git != None %}<div>Git: <a class="text-muted" href="https://github.com/{{author.git}}" target="_blank">{{ author.git }}</a></div>{% endif %}
							<br>
							<div>
								{% if following %}
									<a class="btn btn-outline-danger" href="{% url 'posts:profile_unfollow' author.username %}" role="button">Отписаться</a>
								{% else %}
									<a class="btn btn-success" href="{% url 'posts:profile_follow' author.username %}" role="button">Подписаться</a>
								{% endif %}
							</div>
						</article>
					</div>
				{% else %}
					<div class="row">
						<aside class="col-md-4">
							{% thumbnail author.profile_pic "300x300" crop="center" upscale=True as im %}
								<img class="rounded mx-auto d-block" src="{{ im.url }}"><br>
							{% endthumbnail %}
						</aside>
						<article class="col-md-8">
							<h1>Все мои записи</h1>
							<h6>Всего моих записей: {{ author.posts.count }}</h6>
							<h6>Подписчиков: {{ author.following.count }}</h6>
							{% if author.city != None %}<div>Город: {{ author.city }}</div>{% endif %}
							{% if author.vk != None %}<div>Вконтакте: <a class="text-muted" href="https://vk.com/{{author.vk}}" target="_blank">{{ author.vk }}</a></div>{% endif %}
							{% if author.telegram != None %}<div>Telegram: <a class="text-muted" href="https://t.me/{{author.telegram}}" target="_blank">{{ author.telegram }}</a></div>{% endif %}
							{% if author.instagram != None %}<div>Instagram: <a class="text-muted"  href="https://instagram.com/{{author.instagram}}" target="_blank">{{ author.instagram }}</a></div>{% endif %}
							{% if author.git != None %}<div>Git: <a class="text-muted"  href="https://github.com/{{author.git}}" target="_blank">{{ author.git }}</a></div>{% endif %}
							<br>
							<div>
								<a class="btn btn-outline-success" href="{% url 'users:change' %}">Изменить профиль</a>
							</div>
						</article>
					</div>
				{% endif %}
			</div>
    </div>
		<br>
    {% for post in page_obj %}
    {% include 'posts/includes/post_card.html' %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}