yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('change/', views.change, name='change'),
    path('logout/', views.logout_view,
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_change/',
         PasswordChangeView
         .as_view(template_name='users/password_change_form.html'),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView
         .as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         PasswordResetView
         .as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView
         .as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView
         .as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView
         .as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    profile_pic = models.ImageField(
        'Аватарка',
        default='users/default.jpeg',
        upload_to='users/',
        null=True, blank=True,
        help_text='Добавить аватарку',
    )
    city = models.CharField('Город', max_length=50, null=True, blank=True)
    vk = models.CharField('Вконтакте', max_length=50, null=True, blank=True)
    telegram = models.CharField(
        'Telegram',
        max_length=50,
        null=True, blank=True,
    )
    instagram = models.CharField(
        'Instagram',
        max_length=50,
        null=True, blank=True,
    )
    git = models.CharField('Git', max_length=50, null=True, blank=True)

    class Meta:
        db_table = 'auth_user'
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self):
        return self.username

yatube/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class CreationForm(UserCreationForm):
    class Meta:
        model = User

        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Ваше ник'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'Ваше имя'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Ваша фамилия'}),
            'email': forms.TextInput(attrs={'placeholder': 'Ваш e-mail'}),
            'city': forms.TextInput(attrs={'placeholder': 'Ваш город'}),
            'vk': forms.TextInput(attrs={'placeholder': 'Ваш ник Вконтакте'}),
            'telegram': forms.TextInput(
                attrs={'placeholder': 'Ваш ник в Telegram'}
            ),
            'instagram': forms.TextInput(
                attrs={'placeholder': 'Ваш ник в Instagram'}
            ),
            'git': forms.TextInput(attrs={'placeholder': 'Ваш ник на github'}),
        }

        fields = (
            'username',
            'password1',
            'password2',
            'first_name',
            'last_name',
            'email',
            'profile_pic',
            'city',
            'vk',
            'telegram',
            'instagram',
            'git'
        )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Ваше имя'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Ваша фамилия'}),
            'email': forms.TextInput(attrs={'placeholder': 'Ваш e-mail'}),
            'city': forms.TextInput(attrs={'placeholder': 'Ваш город'}),
            'vk': forms.TextInput(attrs={'placeholder': 'Ваш ник Вконтакте'}),
            'telegram': forms.TextInput(
                attrs={'placeholder': 'Ваш ник в Telegram'}
            ),
            'instagram': forms.TextInput(
                attrs={'placeholder': 'Ваш ник в Instagram'}
            ),
            'git': forms.TextInput(attrs={'placeholder': 'Ваш ник на github'}),
        }

        fields = (
            'first_name',
            'last_name',
            'email',
            'profile_pic',
            'city',
            'vk',
            'telegram',
            'instagram',
            'git'
        )

yatube/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import CreationForm, UserUpdateForm


def logout_view(request):
    logout(request)
    return redirect('posts:index')


def register(request):
    """Функция создания пользователя."""
    form = CreationForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        form.save()
        form.cleaned_data.get('username')
        new_user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'],
        )
        login(request, new_user)
        return redirect('posts:index')
    else:
        form = CreationForm()
    return render(request, 'users/signup.html', {'form': form})


@login_required
def change(request):
    """Функция редактирования пользователя."""
    form = UserUpdateForm(
        request.POST or None,
        files=request.FILES or None,
        instance=request.user
    )
    if form.is_valid():
        form.save()
        return redirect('posts:profile', request.user.username)
    else:
        form = UserUpdateForm(instance=request.user)
    return render(request, 'users/change.html', {'form': form})

yatube/templates/users/change.html
{% extends "base.html" %}
	{% block title %}Изменить профиль{% endblock %}
	{% block content %}
		<div class="container py-4">
			<div class="row justify-content-center">
				<div class="col-md-8">
					<div class="card">
						<div class="card-header">Изменить данные</div>
							<div class="card-body">
								{% include 'includes/errors.html' %}
								<form method="post" action="{% url 'users:change' %}" enctype="multipart/form-data">
									{% csrf_token %}
									{% include 'includes/forms.html' %}
										<div class="d-flex justify-content-center">
											<button type="submit" class="btn btn-success">Изменить данные</button>
										</div>
								</form>
							</div>
						</div>
					</div>
			</div>
		</div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="container py-4">
    <div class="row justify-content-center">
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">Войти на сайт</div>
          <div class="card-body">
            {% include 'includes/errors.html' %}
            <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
            {% csrf_token %}
            {% include 'includes/forms.html' %}
            <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-success">Войти</button>
              <a href="{% url 'users:password_reset' %}" class="btn btn-link text-muted">Забыли пароль?</a>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменен{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body"> 
            <p>Пароль изменён успешно</p>
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div> 
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  <div class="container py-4">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'users:password_change' %}">
              {% csrf_token %}
              {% include 'includes/forms.html' %}
              <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-dark">Изменить пароль</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошел успешно{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">войти</a>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  <div class="container py-5"> 
    {% if validlink %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Введите новый пароль
            </div>
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                {% include 'includes/forms.html' %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-dark">Назначить новый пароль</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    {% else %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Ошибка
            </div>
            <div class="card-body">
              <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошел успешно{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Отправлено письмо
          </div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-4">
    <div class="row justify-content-center">
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body"> 
            <form method="post" action="{% url 'users:password_reset' %}">
            {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>    
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-dark">Сбросить пароль</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>  
  </div>
{% endblock %}

yatube/templates/users/profile.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Мой профиль{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-md-4">
        <h1>{{ user.username }}</h1>
        <img class="rounded mx-auto d-block" src="{{ user.profile.profile_pic.url }}">
      </aside>
      <article class="col-md-8">
        <div class="card">
          <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
                <legend class="border-bottom mb-4">Мои данные</legend>
                {% for field in u_form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                    {% endif %}
                </div>
                {% endfor %}
                  {% for field in p_form %} 
                  <div class="form-group row my-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}
                          <span class="required text-danger">*</span>
                        {% endif %}
                    </label>
                    {{ field|addclass:'form-control' }} 
                      {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                      {% endif %}
                  </div>
                  {% endfor %}
              <div class="form-group">
                  <button class="btn btn-outline-success" type="submit">Обновить данные</button>
              </div>
          </div>
        </div>
      </article>
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="container py-4">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">
              {% include 'includes/errors.html' %}
              <form method="post" action="{% url 'users:signup' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'includes/forms.html' %}
                <div class="d-flex justify-content-center">
                  <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                </div>
              </form>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}